version: '3.7'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports: 
      - "9411:9411"
    networks:
      - bankaya-network
  naming-server:
    image: bankaya/naming-server-image
    ports: 
      - "8761:8761"
    networks:
      - bankaya-network
    depends_on: 
      - zipkin-server
  api-gateway:
    image: bankaya/api-gateway-image
    ports:
      - "8765:8765"
    networks:
      - bankaya-network
    depends_on:
      - naming-server
    environment:
      NAMING_SERVER_HOST: naming-server
      NAMING_SERVER_PORT: 8761
      ZIPKIN_SERVER_HOST: zipkin-server
      ZIPKIN_SERVER_PORT: 9411
  pokemon-soap:
    image: bankaya/pokemon-soap-image
    ports:
      - "8080:8080"
    networks:
      - bankaya-network
    depends_on: 
      - naming-server
    environment:
      NAMING_SERVER_HOST: naming-server
      NAMING_SERVER_PORT: 8761
      ZIPKIN_SERVER_HOST: zipkin-server
      ZIPKIN_SERVER_PORT: 9411
networks:
  bankaya-network:
    external: false